{
  "cveId": "CVE-2022-23097",
  "version": "1.0.0",
  "timestamp": "2024-12-15T20:24:27.876763+00:00",
  "description": "An issue was discovered in the DNS proxy in Connman through 1.40. forward_dns_reply mishandles a strnlen call, leading to an out-of-bounds read.",
  "keyphrases": {
    "rootcause": "mishandles a strnlen call",
    "weakness": "out-of-bounds read",
    "impact": "",
    "vector": "",
    "attacker": "",
    "product": "Connman",
    "version": "through 1.40",
    "component": "DNS proxy"
  },
  "mitreTechnicalImpacts": []
}