{
    "cveId": "CVE-2020-24583",
    "version": "1.0.0",
    "timestamp": "2024-12-13T17:34:55.850537+00:00",
    "description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "",
        "impact": "",
        "vector": "",
        "attacker": "",
        "product": "Django",
        "version": "2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1",
        "component": ""
    }
}
