{
  "cveId": "CVE-2014-3730",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by http\\\\\\djangoproject.com.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "open redirect",
    "impact": "open redirect attacks",
    "vector": "malformed URL",
    "attacker": "remote attackers",
    "product": "Django",
    "version": [
      "1.4 before 1.4.13",
      "1.5 before 1.5.8",
      "1.6 before 1.6.5",
      "and 1.7 before 1.7b4"
    ],
    "component": "django.util.http.is_safe_url function"
  },
  "mitreTechnicalImpacts": []
}