{
  "cveId": "CVE-2012-2135",
  "version": "1.0.0",
  "timestamp": "2024-12-10T17:54:04.992951+00:00",
  "description": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "improper memory management",
    "impact": [
      "information disclosure or denial of service",
      "obtain sensitive information"
    ],
    "vector": "unspecified vectors",
    "attacker": "remote attackers",
    "product": "Python",
    "version": "3.1 through 3.3",
    "component": "utf-16 decoder"
  },
  "mitreTechnicalImpacts": []
}