{
  "cveId": "CVE-2021-29548",
  "version": "1.0.0",
  "timestamp": "2024-12-15T20:24:27.876763+00:00",
  "description": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a runtime division by zero error and denial of service in `tf.raw_ops.QuantizedBatchNormWithGlobalNormalization`. This is because the implementation(https//github.com/tensorflow/tensorflow/blob/55a97caa9e99c7f37a0bbbeb414dc55553d3ae7f/tensorflow/core/kernels/quantized_batch_norm_op.cc) does not validate all constraints specified in the ops contract(https//www.tensorflow.org/api_docs/python/tf/raw_ops/QuantizedBatchNormWithGlobalNormalization). The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.",
  "keyphrases": {
    "rootcause": "does not validate all constraints specified in the ops contract",
    "weakness": "division by zero",
    "impact": [
      "['runtime division by zero error'",
      "'denial of service']"
    ],
    "vector": "",
    "attacker": "attacker",
    "product": "TensorFlow",
    "version": "2.5.0",
    "component": "tf.raw_ops.QuantizedBatchNormWithGlobalNormalization"
  },
  "mitreTechnicalImpacts": []
}