{
    "cveId": "CVE-2023-26052",
    "version": "1.0.0",
    "timestamp": "2024-12-15T20:24:27.876763+00:00",
    "description": "Saleor is a headless, GraphQL commerce platform delivering personalized shopping experiences. Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests. This issue has been patched in versions 3.1.48, 3.7.59, 3.8.0, 3.9.27, 3.10.14 and 3.11.12.",
    "keyphrases": {
        "rootcause": "internal Python exceptions are not handled properly",
        "weakness": "",
        "impact": "return sensitive information in API error messages",
        "vector": "unauthenticated requests",
        "attacker": "",
        "product": "Saleor",
        "version": "3.1.48, 3.7.59, 3.8.0, 3.9.27, 3.10.14 and 3.11.12",
        "component": ""
    }
}
