{
    "cveId": "CVE-2024-53432",
    "version": "1.0.0",
    "timestamp": "2024-12-17T08:36:27.567979+00:00",
    "description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught stdout_of_range exception in PCLPointCloud2at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "uncaught stdout_of_range exception",
        "impact": "denial-of-service (DoS)",
        "vector": "malformed PLY files",
        "attacker": "",
        "product": "PCL",
        "version": "1.14.1",
        "component": "PCLPointCloud2at"
    }
}
