{
  "cveId": "CVE-2020-8192",
  "version": "1.0.0",
  "timestamp": "2024-12-13T17:34:55.850537+00:00",
  "description": "A denial of service vulnerability exists in Fastify v2.14.1 and v3.0.0-rc.4 that allows a malicious user to trigger resource exhaustion (when the allErrors option is used) with specially crafted schemas.",
  "keyphrases": {
    "rootcause": "A denial of service vulnerability exists",
    "weakness": "",
    "impact": "denial of service",
    "vector": "specially crafted schemas",
    "attacker": "malicious user",
    "product": "Fastify",
    "version": "v2.14.1 and v3.0.0-rc.4",
    "component": ""
  },
  "mitreTechnicalImpacts": []
}